### ISSUE TITLE
Register token with emoji on Unknown Tokens screen is not working

### ISSUE THREAD

**Issue by pedroferreira1** [HathorNetwork/hathor-wallet#69]
PR: https://github.com/HathorNetwork/hathor-wallet/pull/70

Error:

```
Error Message: object null is not iterable (cannot read property Symbol(Symbol.iterator))
Stack trace: TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at ModalAddManyTokens._this.handleAdd (http://localhost:3000/static/js/main.chunk.js:2024:37)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/0.chunk.js:118952:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/0.chunk.js:119001:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/0.chunk.js:119055:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/0.chunk.js:119070:29)
    at executeDispatch (http://localhost:3000/static/js/0.chunk.js:119376:7)
    at executeDispatchesInOrder (http://localhost:3000/static/js/0.chunk.js:119401:9)
    at executeDispatchesAndRelease (http://localhost:3000/static/js/0.chunk.js:119500:9)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3000/static/js/0.chunk.js:119509:14)
    at forEachAccumulated (http://localhost:3000/static/js/0.chunk.js:119481:12)
    at runEventsInBatch (http://localhost:3000/static/js/0.chunk.js:119649:7)
    at runExtractedEventsInBatch (http://localhost:3000/static/js/0.chunk.js:119657:7)
    at handleTopLevel (http://localhost:3000/static/js/0.chunk.js:123835:9)
    at batchedUpdates$1 (http://localhost:3000/static/js/0.chunk.js:140274:16)
    at batchedUpdates (http://localhost:3000/static/js/0.chunk.js:121052:16)
    at dispatchEvent (http://localhost:3000/static/js/0.chunk.js:123915:9)
    at http://localhost:3000/static/js/0.chunk.js:140331:18
    at Object.unstable_runWithPriority (http://localhost:3000/static/js/0.chunk.js:155805:16)
    at interactiveUpdates$1 (http://localhost:3000/static/js/0.chunk.js:140330:26)
    at interactiveUpdates (http://localhost:3000/static/js/0.chunk.js:121073:14)
    at dispatchInteractiveEvent (http://localhost:3000/static/js/0.chunk.js:123891:7)
```

**Comment by msbrogli** [comment]
The PR was merged.
